apiVersion: v1
kind: Service
metadata:
  name: drupal-8-db
  labels:
    app: drupal-8  
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    name: drupal-8-db
    app: drupal-8  
