apiVersion: v1
kind: DeploymentConfig
metadata:
  name: drupal-8-db
  labels:
    app: drupal-8  
spec:
  replicas: 1
  selector:
    name: drupal-8-db
    app: drupal-8    
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: drupal-8-db
        app: drupal-8  
    spec:
      containers:
      - env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: drupal-8
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: drupal-8
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-root-password
              name: drupal-8
        - name: MYSQL_DATABASE
          value: drupal8
        image: ' '
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3306
          timeoutSeconds: 1
        name: mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE
              -e 'SELECT 1'
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql/data
          name: drupal-8-db-data
      volumes:
      - name: drupal-8-db-data
        persistentVolumeClaim:
          claimName: drupal-8-db
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - mysql
      from:
        kind: ImageStreamTag
        name: mariadb:10.2
        namespace: openshift
    type: ImageChange
  - type: ConfigChange
