apiVersion: v1
kind: DeploymentConfig
metadata:
  name: drupal-8
  labels:
    app: drupal-8
spec:
  replicas: 1
  selector:
    app: drupal-8
  template:
    metadata:
      labels:
        app: drupal-8
    spec:
      volumes:
        # Create the shared files volume to be used in both pods
        - name: app
          emptyDir: {}
        - name: drupal-8-files
          persistentVolumeClaim:
            claimName: drupal-8-files
      containers:
      - name: php-fpm
        image: 'lakshminp/drupal-openshift:1.0'
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: drupal-8
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: drupal-8
        - name: MYSQL_HOST
          value: drupal-8-db
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: drupal8
        - name: OPENSHIFT_BUILD_NAME
          value: "1"
        volumeMounts:
          - name: app
            mountPath: /app
          - name: drupal-8-files
            mountPath: /shared
        lifecycle:
          postStart:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - > 
                  cp -fr /code/. /app;
                  rm -rf /app/web/sites/default/files;
                  ln -s /shared /app/web/sites/default/files;
      - name: nginx
        image: 'lakshminp/nginx-openshift:1.0'
        ports:
          - name: http
            containerPort: 8080
        volumeMounts:
          - name: app
            mountPath: /app
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - php-fpm
        from:
          kind: "ImageStreamTag"
          name: "drupal-openshift:latest"
          namespace: openshift
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - nginx
        from:
          kind: "ImageStreamTag"
          name: "nginx-openshift:latest"
          namespace: openshift
