apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: apache-rs
  labels:
    app: demo1
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: demo1
    matchExpressions: 
      - {key: app, operator: In, values: [demo1]}
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
      - name: webserver
        image: lakshminp/apache:v2
        ports:
        - name: http
          containerPort: 8080
      restartPolicy: Always
