apiVersion: v1
kind: Pod
metadata:
  name: php-fpm-nginx
  labels:
    app: php-fpm-nginx
spec:
  volumes:
    # Create the shared files volume to be used in both pods
    - name: app
      emptyDir: {}
  containers:
    - name: php-fpm
      image: lakshminp/drupal-openshift
      volumeMounts:
        - name: app
          mountPath: /app
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh", "-c", "cp -r /code/. /app"]
    - name: nginx
      image: lakshminp/nginx-openshift
      ports:
        - name: http
          containerPort: 8080
      volumeMounts:
        - name: app
          mountPath: /app
